# frozen_string_literal: true

module Aireview
  class ReviewRenderer
    MISMATCH_LIMIT = 2
    IMPORTANT_LIMIT = 3
    TOTAL_FINDINGS_LIMIT = 3
    IMPORTANT_CATEGORIES = %w[
      bug
      regression
      security
      performance
      data_loss
      edge_case
    ].freeze

    SEVERITY_ORDER = {
      'critical' => 0,
      'major' => 1,
      'minor' => 2
    }.freeze

    DEFAULT_LANGUAGE = 'en'
    LABELS = {
      'en' => {
        summary: 'Summary',
        mismatches: 'Mismatches',
        important: 'Important findings',
        result: 'Result',
        disclaimer: 'This report was generated by an AI and may contain mistakes. ' \
                    'Verify the findings by hand before acting on them.',
        no_summary: 'The first pass did not return a summary of the changes.',
        none_found: 'None found.',
        not_specified: 'Not specified.',
        where: 'Where',
        problem: 'Problem',
        why: 'Why it matters',
        suggestion: 'Suggestion',
        partial: 'Partial review',
        not_reviewed: 'Not reviewed',
        files_not_shown: 'files not reviewed',
        files_partial: 'files reviewed partially',
        files_unavailable: 'files without an available diff',
        sections_truncated: 'sections truncated',
        hunks_of: 'hunks shown',
        diff_unavailable: 'diff not available',
        section_list: 'Truncated sections'
      },
      'ru' => {
        summary: 'Сводка',
        mismatches: 'Несоответствия',
        important: 'Важные замечания',
        result: 'Результат',
        disclaimer: 'Отчёт сгенерирован ИИ и может содержать ошибки. ' \
                    'Проверьте замечания вручную перед принятием решений.',
        no_summary: 'Сводка изменений не была возвращена на первом проходе.',
        none_found: 'Не найдено.',
        not_specified: 'Не указано.',
        where: 'Где',
        problem: 'Проблема',
        why: 'Почему важно',
        suggestion: 'Предложение',
        partial: 'Ревью частичное',
        not_reviewed: 'Не вошло в ревью',
        files_not_shown: 'файлов не проверено',
        files_partial: 'файлов проверено частично',
        files_unavailable: 'файлов без доступного диффа',
        sections_truncated: 'секций усечено',
        hunks_of: 'хунков показано',
        diff_unavailable: 'дифф недоступен',
        section_list: 'Усечённые секции'
      }
    }.freeze

    def initialize(language: DEFAULT_LANGUAGE)
      @labels = LABELS.fetch(language.to_s) { LABELS.fetch(DEFAULT_LANGUAGE) }
    end

    # coverage: факты усечения контекста от пайплайна, не текст модели.
    # result по-прежнему про найденные проблемы; неполнота покрытия
    # дописывается рядом с ним, чтобы строка результата не читалась как
    # «проверено всё».
    def render(accepted, summary:, coverage: nil)
      findings = sorted_findings(Array(accepted)).first(TOTAL_FINDINGS_LIMIT)
      mismatches = findings.select { |finding| category(finding) == 'task_mismatch' }.first(MISMATCH_LIMIT)
      important = findings.select { |finding| important_finding?(finding) }.first(IMPORTANT_LIMIT)
      result = mismatches.empty? && important.empty? ? 'ok' : 'needs attention'

      <<~MARKDOWN.rstrip
        ## #{label(:summary)}

        #{summary_text(summary)}

        ## #{label(:mismatches)}

        #{render_findings(mismatches)}

        ## #{label(:important)}

        #{render_findings(important)}

        ## #{label(:result)}

        #{result}#{partial_note(coverage)}
        #{coverage_block(coverage)}
        #{label(:disclaimer)}
      MARKDOWN
    end

    private

    def sorted_findings(findings)
      findings
        .grep(Hash)
        .sort_by { |finding| [SEVERITY_ORDER.fetch(severity(finding), 99), value(finding, 'id').to_s] }
    end

    def important_finding?(finding)
      return false if category(finding) == 'task_mismatch'
      return false if severity(finding) == 'minor'

      IMPORTANT_CATEGORIES.include?(category(finding))
    end

    def summary_text(summary)
      presence(summary) || label(:no_summary)
    end

    def render_findings(findings)
      return label(:none_found) if findings.empty?

      findings.map do |finding|
        <<~ITEM.rstrip
          - **#{label(:where)}**: #{location(finding)}
          - **#{label(:problem)}**: #{presence(value(finding, 'problem')) || label(:not_specified)}
          - **#{label(:why)}**: #{presence(value(finding, 'why')) || label(:not_specified)}
          - **#{label(:suggestion)}**: #{presence(value(finding, 'suggestion')) || label(:not_specified)}
        ITEM
      end.join("\n\n")
    end

    def partial_note(coverage)
      return '' if coverage.nil? || coverage.complete?

      counts = {
        files_not_shown: coverage.files_not_shown.size,
        files_partial: coverage.files_partial.size,
        files_unavailable: coverage.files_unavailable.size,
        sections_truncated: coverage.truncated_sections.size
      }.reject { |_, count| count.zero? }.map { |key, count| "#{count} #{label(key)}" }

      ". #{label(:partial)}: #{counts.join(', ')}."
    end

    def coverage_block(coverage)
      return '' if coverage.nil? || coverage.complete?

      lines = coverage.files_not_shown.map { |path| "- #{path}" }
      lines += coverage.files_partial.map do |file|
        "- #{file[:path]}: #{file[:shown]}/#{file[:total]} #{label(:hunks_of)}"
      end
      lines += coverage.files_unavailable.map { |path| "- #{path}: #{label(:diff_unavailable)}" }
      unless coverage.truncated_sections.empty?
        lines << "- #{label(:section_list)}: #{coverage.truncated_sections.join(', ')}"
      end

      "\n## #{label(:not_reviewed)}\n\n#{lines.join("\n")}\n"
    end

    def location(finding)
      file = presence(value(finding, 'file'))
      line = value(finding, 'line')
      return label(:not_specified) unless file
      return file if line.nil? || line.to_s.empty?

      "#{file}:#{line}"
    end

    def label(key)
      @labels.fetch(key)
    end

    def value(hash, key)
      hash[key] || hash[key.to_sym]
    end

    def category(finding)
      value(finding, 'category').to_s.downcase
    end

    def severity(finding)
      value(finding, 'severity').to_s.downcase
    end

    def presence(value)
      string = value.to_s.strip
      string.empty? ? nil : string
    end
  end
end
