require 'aireview/review_renderer'
require 'aireview/context_budget'

RSpec.describe Aireview::ReviewRenderer do
  let(:finding) do
    {
      'id' => 'C1',
      'file' => 'app/models/order.rb',
      'line' => 12,
      'category' => 'bug',
      'severity' => 'major',
      'problem' => 'Tax is no longer included',
      'why' => 'Breaks checkout',
      'suggestion' => 'Keep the previous calculation'
    }
  end

  it 'renders English labels by default' do
    result = described_class.new.render([finding], summary: 'Recalculates totals')

    expect(result).to include('## Summary', '## Mismatches', 'None found.', '## Important findings')
    expect(result).to include('- **Where**: app/models/order.rb:12')
    expect(result).to include('- **Problem**: Tax is no longer included')
    expect(result).to include('- **Why it matters**: Breaks checkout')
    expect(result).to include('- **Suggestion**: Keep the previous calculation')
    expect(result).to include('## Result', 'needs attention')
    expect(result).to include('This report was generated by an AI')
  end

  it 'renders Russian labels for the ru language' do
    result = described_class.new(language: 'ru').render([finding], summary: 'Пересчёт итогов')

    expect(result).to include('## Сводка', '## Несоответствия', 'Не найдено.', '## Важные замечания')
    expect(result).to include('- **Где**: app/models/order.rb:12')
    expect(result).to include('- **Проблема**: Tax is no longer included')
    expect(result).to include('- **Почему важно**: Breaks checkout')
    expect(result).to include('- **Предложение**: Keep the previous calculation')
    expect(result).to include('## Результат', 'needs attention')
    expect(result).to include('Отчёт сгенерирован ИИ')
  end

  it 'falls back to English labels for an unknown language' do
    result = described_class.new(language: 'de').render([], summary: nil)

    expect(result).to include('## Summary', 'The first pass did not return a summary of the changes.')
    expect(result).to include('None found.', 'ok')
  end

  it 'reports partial coverage next to the result and in a separate block' do
    coverage = Aireview::ContextBudget::Coverage.empty
    coverage.files_not_shown.push('app/a.rb', 'app/b.rb')
    coverage.files_partial << { path: 'app/c.rb', shown: 2, total: 5 }
    coverage.files_unavailable << 'assets/logo.png'
    coverage.truncated_sections << 'Jira description'

    result = described_class.new.render([], summary: 'Recalculates totals', coverage: coverage)

    expect(result).to include(
      "ok. Partial review: 2 files not reviewed, 1 files reviewed partially, " \
      '1 files without an available diff, 1 sections truncated.'
    )
    expect(result).to include(<<~BLOCK)
      ## Not reviewed

      - app/a.rb
      - app/b.rb
      - app/c.rb: 2/5 hunks shown
      - assets/logo.png: diff not available
      - Truncated sections: Jira description
    BLOCK
    expect(result.index('## Not reviewed')).to be > result.index('## Result')
    expect(result.index('This report was generated')).to be > result.index('## Not reviewed')
  end

  it 'keeps the result about findings and renders coverage labels in Russian' do
    coverage = Aireview::ContextBudget::Coverage.empty
    coverage.files_not_shown << 'app/a.rb'

    result = described_class.new(language: 'ru').render([finding], summary: 'x', coverage: coverage)

    expect(result).to include('needs attention. Ревью частичное: 1 файлов не проверено.')
    expect(result).to include("## Не вошло в ревью\n\n- app/a.rb")
  end

  it 'renders nothing about coverage when it is complete' do
    complete = described_class.new.render([], summary: 'x', coverage: Aireview::ContextBudget::Coverage.empty)

    expect(complete).to eq(described_class.new.render([], summary: 'x'))
    expect(complete).not_to include('Partial review', 'Not reviewed')
  end

  it 'uses placeholders for missing finding fields' do
    result = described_class.new.render([finding.merge('file' => nil, 'why' => '')], summary: 'x')

    expect(result).to include('- **Where**: Not specified.')
    expect(result).to include('- **Why it matters**: Not specified.')
  end
end
