require 'aireview/review_renderer'

RSpec.describe Aireview::ReviewRenderer do
  let(:finding) do
    {
      'id' => 'C1',
      'file' => 'app/models/order.rb',
      'line' => 12,
      'category' => 'bug',
      'severity' => 'major',
      'problem' => 'Tax is no longer included',
      'why' => 'Breaks checkout',
      'suggestion' => 'Keep the previous calculation'
    }
  end

  it 'renders English labels by default' do
    result = described_class.new.render([finding], summary: 'Recalculates totals')

    expect(result).to include('## Summary', '## Mismatches', 'None found.', '## Important findings')
    expect(result).to include('- **Where**: app/models/order.rb:12')
    expect(result).to include('- **Problem**: Tax is no longer included')
    expect(result).to include('- **Why it matters**: Breaks checkout')
    expect(result).to include('- **Suggestion**: Keep the previous calculation')
    expect(result).to include('## Result', 'needs attention')
    expect(result).to include('This report was generated by an AI')
  end

  it 'renders Russian labels for the ru language' do
    result = described_class.new(language: 'ru').render([finding], summary: 'Пересчёт итогов')

    expect(result).to include('## Сводка', '## Несоответствия', 'Не найдено.', '## Важные замечания')
    expect(result).to include('- **Где**: app/models/order.rb:12')
    expect(result).to include('- **Проблема**: Tax is no longer included')
    expect(result).to include('- **Почему важно**: Breaks checkout')
    expect(result).to include('- **Предложение**: Keep the previous calculation')
    expect(result).to include('## Результат', 'needs attention')
    expect(result).to include('Отчёт сгенерирован ИИ')
  end

  it 'falls back to English labels for an unknown language' do
    result = described_class.new(language: 'de').render([], summary: nil)

    expect(result).to include('## Summary', 'The first pass did not return a summary of the changes.')
    expect(result).to include('None found.', 'ok')
  end

  it 'uses placeholders for missing finding fields' do
    result = described_class.new.render([finding.merge('file' => nil, 'why' => '')], summary: 'x')

    expect(result).to include('- **Where**: Not specified.')
    expect(result).to include('- **Why it matters**: Not specified.')
  end
end
